-- MySQL Script generated by MySQL Workbench
-- Fri May  7 01:02:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Propietario` (
  `idClub` INT NOT NULL AUTO_INCREMENT,
  `nombreClub` VARCHAR(45) NOT NULL,
  `localización` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `alta` INT NOT NULL,
  PRIMARY KEY (`idClub`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deportes` (
  `idDeportes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numeroJugadores` INT NOT NULL,
  PRIMARY KEY (`idDeportes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pistas` (
  `idPista` INT NOT NULL AUTO_INCREMENT,
  `idClub` INT NOT NULL,
  `horarioInicio` TIME NOT NULL,
  `horarioFin` TIME NOT NULL,
  `precioHora` DECIMAL(4,2) NOT NULL,
  `puntuacionMedia` INT NULL,
  `Propietario_idClub` INT NOT NULL,
  `Deportes_idDeportes` INT NOT NULL,
  PRIMARY KEY (`idPista`, `Propietario_idClub`),
  INDEX `fk_Pistas_Propietario1_idx` (`Propietario_idClub` ASC) VISIBLE,
  INDEX `fk_Pistas_Deportes1_idx` (`Deportes_idDeportes` ASC) VISIBLE,
  CONSTRAINT `fk_Pistas_Propietario1`
    FOREIGN KEY (`Propietario_idClub`)
    REFERENCES `mydb`.`Propietario` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pistas_Deportes1`
    FOREIGN KEY (`Deportes_idDeportes`)
    REFERENCES `mydb`.`Deportes` (`idDeportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `Pistas_idPista` INT NOT NULL,
  `Pistas_Propietario_idClub` INT NOT NULL,
  `Pistas_idPista1` INT NOT NULL,
  `Pistas_Propietario_idClub1` INT NOT NULL,
  PRIMARY KEY (`idReservas`, `Pistas_idPista`, `Pistas_Propietario_idClub`),
  INDEX `fk_Reservas_Pistas1_idx` (`Pistas_idPista1` ASC, `Pistas_Propietario_idClub1` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_Pistas1`
    FOREIGN KEY (`Pistas_idPista1` , `Pistas_Propietario_idClub1`)
    REFERENCES `mydb`.`Pistas` (`idPista` , `Propietario_idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partidos` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `fechayHora` DATETIME NOT NULL,
  `idPista` INT NOT NULL,
  `idcreador` INT NOT NULL,
  `nivelPartido` DECIMAL NULL,
  `Reservas_idReservas` INT NOT NULL,
  `Reservas_Pistas_idPista` INT NOT NULL,
  `Reservas_Pistas_Propietario_idClub` INT NOT NULL,
  `Reservas_idReservas1` INT NOT NULL,
  `Reservas_Pistas_idPista1` INT NOT NULL,
  `Reservas_Pistas_Propietario_idClub1` INT NOT NULL,
  PRIMARY KEY (`idPartido`, `Reservas_idReservas`, `Reservas_Pistas_idPista`, `Reservas_Pistas_Propietario_idClub`, `Reservas_idReservas1`, `Reservas_Pistas_idPista1`, `Reservas_Pistas_Propietario_idClub1`),
  INDEX `fk_Partidos_Reservas1_idx` (`Reservas_idReservas1` ASC, `Reservas_Pistas_idPista1` ASC, `Reservas_Pistas_Propietario_idClub1` ASC) VISIBLE,
  CONSTRAINT `fk_Partidos_Reservas1`
    FOREIGN KEY (`Reservas_idReservas1` , `Reservas_Pistas_idPista1` , `Reservas_Pistas_Propietario_idClub1`)
    REFERENCES `mydb`.`Reservas` (`idReservas` , `Pistas_idPista` , `Pistas_Propietario_idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PartidoJugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PartidoJugador` (
  `idPartidoJugador` INT NOT NULL,
  `Partidos_idPartido` INT NOT NULL,
  `Partidos_Reservas_idReservas` INT NOT NULL,
  `Partidos_Reservas_Pistas_idPista` INT NOT NULL,
  `Partidos_Reservas_Pistas_Propietario_idClub` INT NOT NULL,
  PRIMARY KEY (`idPartidoJugador`),
  INDEX `fk_PartidoJugador_Partidos1_idx` (`Partidos_idPartido` ASC, `Partidos_Reservas_idReservas` ASC, `Partidos_Reservas_Pistas_idPista` ASC, `Partidos_Reservas_Pistas_Propietario_idClub` ASC) VISIBLE,
  CONSTRAINT `fk_PartidoJugador_Partidos1`
    FOREIGN KEY (`Partidos_idPartido` , `Partidos_Reservas_idReservas` , `Partidos_Reservas_Pistas_idPista` , `Partidos_Reservas_Pistas_Propietario_idClub`)
    REFERENCES `mydb`.`Partidos` (`idPartido` , `Reservas_idReservas` , `Reservas_Pistas_idPista` , `Reservas_Pistas_Propietario_idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jugadores` (
  `idJugador` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATETIME NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `teléfono` INT NULL,
  `PartidoJugador_idPartidoJugador` INT NOT NULL,
  PRIMARY KEY (`idJugador`),
  INDEX `fk_Jugadores_PartidoJugador1_idx` (`PartidoJugador_idPartidoJugador` ASC) VISIBLE,
  CONSTRAINT `fk_Jugadores_PartidoJugador1`
    FOREIGN KEY (`PartidoJugador_idPartidoJugador`)
    REFERENCES `mydb`.`PartidoJugador` (`idPartidoJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puntuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puntuaciones` (
  `idPuntuaciones` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` INT NOT NULL,
  `Comentario` TEXT(240) NULL,
  `Pistas_idPista` INT NOT NULL,
  `Pistas_Propietario_idClub` INT NOT NULL,
  `Jugadores_idJugador` INT NOT NULL,
  PRIMARY KEY (`idPuntuaciones`, `Pistas_idPista`, `Pistas_Propietario_idClub`),
  INDEX `fk_Puntuaciones_Pistas1_idx` (`Pistas_idPista` ASC, `Pistas_Propietario_idClub` ASC) VISIBLE,
  INDEX `fk_Puntuaciones_Jugadores1_idx` (`Jugadores_idJugador` ASC) VISIBLE,
  CONSTRAINT `fk_Puntuaciones_Pistas1`
    FOREIGN KEY (`Pistas_idPista` , `Pistas_Propietario_idClub`)
    REFERENCES `mydb`.`Pistas` (`idPista` , `Propietario_idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puntuaciones_Jugadores1`
    FOREIGN KEY (`Jugadores_idJugador`)
    REFERENCES `mydb`.`Jugadores` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valoraciones_jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Valoraciones_jugadores` (
  `idValoraciones` INT NOT NULL AUTO_INCREMENT,
  `idUsuarioValorador` INT NOT NULL,
  `puntuación` INT NOT NULL,
  `Jugadores_idJugador` INT NOT NULL,
  PRIMARY KEY (`idValoraciones`, `Jugadores_idJugador`),
  INDEX `fk_Valoraciones_jugadores_Jugadores1_idx` (`Jugadores_idJugador` ASC) VISIBLE,
  CONSTRAINT `fk_Valoraciones_jugadores_Jugadores1`
    FOREIGN KEY (`Jugadores_idJugador`)
    REFERENCES `mydb`.`Jugadores` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
